baseURL = "https://gonzalo.f-v.es/"
languageCode = "en-us"
theme = "hugo-theme-codex"
copyright = "© Gonzalo Fernandez-Victorio {year}"
defaultContentLanguage = "en"
publishDir = "docs"
summaryLength = 30
enableRobotsTXT = true

[taxonomies]
  category = "categories"
  tag = "tags"
[params]
  author = "Gonzalo Fernandez-Victorio"
  description = "Some thoughts about things"
  recent_posts_number = 5
  linkedin = "https://www.linkedin.com/in/gonzalofernandezvictorio/"
  twitter = "https://twitter.com/gonfva"
  github = "https://github.com/gonfva"
  iconOrder = ["Twitter", "GitHub", "LinkedIn"]
  env = "production"
  showPageTitleInTOC = true
  twitterSite = "@gonfva"
  twitterAuthor = "@gonfva"
  dateFormat = "2006-01-02"

[languages]
  [languages.en]
    title = "Gonzalo's thoughts"
    weight = 1
    contentDir = "content/en"

  [languages.es]
    title = "Las cosas de Gonzalo"
    weight = 2
    contentDir = "content/es"

[markup]
  [markup.highlight]
    codeFences = false

  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog-en"
  name = "Blog EN"
  title = "Blog"
  url = "/blog"

[[menu.main]]
  identifier = "blog-es"
  name = "Blog ES"
  title = "Blog"
  url = "/es/blog"
