---
layout: post
title: "It's great when your idea is a good one. But..."
date: 2014-02-26 14:11:36 UTC
updated: 2014-02-26 14:11:36 UTC
comments: false
categories: Developer
---

Since I came to London, more than a year ago, I've been travelling a lot back to Spain. I used to schedule trips in advance, and once I discovered I had two different reserves for the same trip (fortunately I was able to change one of them). Soon I realized I needed some tool to manage the trips.<br /><div><br /></div><div>I did a quick search and I couldn't find anything.<br /><div><br /></div><div>Then my wife and daughters finally came here. And I had even more trips to schedule. We needed to plan well in advance, because trips where more than three times more expensive (when travelling with children I cannot afford to wait queues hoping to get a good seat nor fly to a distant airport to save some pounds). Also, people in Spain started to come and visit us, and we also needed to plan that.</div><div><br /></div><div>So I had my own itch to scratch, which is the better way to commit to something.&nbsp;</div><div><br /></div><div>But my own requirements could be expanded to accommodate similar requirements from businesses. And businesses pay. I had a business plan. Not for the next social network, but for a small web application. I also wanted to practice Rails.&nbsp;</div><div><br /></div><div>So I started to build it. In my own free time. I built a <a href="http://ancient-mountain-9909.herokuapp.com/en/home">quick and dirty prototype</a>. And I started to build something <a href="http://www.whendoigo.co.uk/">more serious</a>.&nbsp;</div><div><br /></div><div>Today I discovered that there is indeed <a href="https://www.tripit.com/">something similar</a>. A quick sign up told me most of the things I envisioned (including emailing confirmations to ease the pain in managing trip status) are already there.&nbsp;</div><div><br /></div><div>And it is made by <a href="https://www.concur.com/">one of the big grands</a> in expense and travel management.</div><div><br /></div><div>Three lessons learned:</div><div><ul><li>Do a proper research.</li><li><a href="http://blog.whendoigo.co.uk/2013/11/30-days.html">Commit</a>. Commit. Commit.</li><li>It's great when your idea is a good one. You're no longer a freak who prefers the cloud to a notebook.</li></ul><div>And yes. I have other ideas. But <a href="http://sivers.org/multiply">ideas are just a multiplier</a>. The question is if I'll be able to commit.</div></div></div>
