---
layout: post
title: "A great experience applying to a position (II)"
date: 2012-08-16 21:59:17 UTC
updated: 2012-08-16 21:59:17 UTC
comments: false
categories: Jobs
---

<span style="font-family: inherit;">In my previous post I explained <a href="http://gonfva.blogspot.com/2012/08/a-great-experience-applying-to-position.html" target="_blank">a great experience applying for a position</a>. In this post I wanted to share what lessons I've learnt from that experience.</span>
<br /><br />
<ol><li>Selection: Be very selective about what you apply for. For me this means no recruiters, making a pre-research of the company, and reading carefully the description to get a sense of what the company is asking. It's pretty obvious, but essential for the following lesson.</li><li>Visa: When applying for a foreign country, make some research about Visa requirements. For example, unless you are a guru, don't apply to an US listing. It's quite difficult to get an sponsorship for the US, but no so for Australia. Are you an&nbsp;European&nbsp;citizen? Doors open in Europe. And so on.</li><li>Target: Carefully target the ad and the company with the cover letter. In my experience this is more important than the CV. CVs doesn't work. I'm in the process of completing a 35 pages CV (no kidding) and I can tell you it won't describe me.&nbsp;</li><li>Try to target the cover letter but be honest and open. There was a great post on 3degrees blog,&nbsp;unfortunately&nbsp;deleted. See <a href="http://www.klektd.com/bookmarks/4fbddcad79893d3f43000009/cached" target="_blank">this cache copy</a>.</li><li>Test, code, refactor: Yes, you know about TDD and BDD. In fact you are expected to send the tests along with the code. But at least in my previous assignments, I had tested, then coded, but I had forgot to refactor to get a nice design. And I had sent code not adequately designed. This time, I set a good set of tests, then hacked something quick, then refactored lots of times.</li><li>Research: For the interview do a great research. Be prepared. Who would be your mates? Nasty comments about the company? Source code of the pages?. And if the interview seems in a loop, (not the case this time), be open but drive it to a point.&nbsp;</li><li>Build a presence online. Most asked request: show us your code. Yes, I have a github account (<a href="https://github.com/gonfva/" target="_blank">actually</a> <a href="https://github.com/crypteasy" target="_blank">two</a>). And I also have a blog (<a href="http://gonfva.blogspot.com/" target="_blank">this one</a> ;D) But at work I don't have the time to build the presence. And doing it at home is quite difficult. But it's essential</li></ol><div>I think fifth and sixth really made a difference, but I'm really starting to learn how to apply to a position.And I'm trying to complete the seventh point. This blog posts are part of that effort.</div>
<br /><br />
